//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender
    {
        public int GenderId { get; set; }
        public string GenderDescription { get; set; }
        public string GenderCode { get; set; }
        public Nullable<bool> IsVoided { get; set; }
    }
}
