//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ictype
    {
        public string ctype { get; set; }
        public string ctypedesc { get; set; }
        public string citemdesc { get; set; }
        public string cfitemdesc { get; set; }
        public string cmeasure { get; set; }
        public string csmeasure { get; set; }
        public string cpmeasure { get; set; }
        public string cclass { get; set; }
        public string cprodline { get; set; }
        public string ccommiss { get; set; }
        public string crevncode { get; set; }
        public string cinvtacc { get; set; }
        public string cintracc { get; set; }
        public string cstatus { get; set; }
        public string ctaxcode { get; set; }
        public short laritem { get; set; }
        public short lpoitem { get; set; }
        public short lmiitem { get; set; }
        public short lioitem { get; set; }
        public short lkititem { get; set; }
        public short lusekitno { get; set; }
        public short llot { get; set; }
        public short lusespec { get; set; }
        public short lchkonhand { get; set; }
        public short lupdonhand { get; set; }
        public short ltaxable1 { get; set; }
        public short ltaxable2 { get; set; }
        public short lallownupd { get; set; }
        public short lallowneg { get; set; }
        public short lnegprice { get; set; }
        public short lowdesc { get; set; }
        public short lowprice { get; set; }
        public short lowdisc { get; set; }
        public short lowtax { get; set; }
        public short lowweight { get; set; }
        public short lowrevncd { get; set; }
        public short lowcomp { get; set; }
        public short lowcoms { get; set; }
        public short lprtsn { get; set; }
        public short lprtlotno { get; set; }
        public short lowivrmk { get; set; }
        public short lptivrmk { get; set; }
        public short lptarpsrmk { get; set; }
        public short lowsormk { get; set; }
        public short lptsormk { get; set; }
        public short lptsoplrmk { get; set; }
        public short lptsopsrmk { get; set; }
        public short lowpormk { get; set; }
        public short lptpormk { get; set; }
        public short lowmirmk { get; set; }
        public short lptmirmk { get; set; }
        public short lowrarmk { get; set; }
        public short lptrarmk { get; set; }
        public short lptraplrmk { get; set; }
        public short ldiscard { get; set; }
        public short lrepair { get; set; }
        public short lprebkit { get; set; }
        public int ncosttype { get; set; }
        public int nqtydec { get; set; }
        public decimal ndiscrate { get; set; }
        public decimal nweight { get; set; }
        public decimal nstdcost { get; set; }
        public decimal nrtrncost { get; set; }
        public decimal nprice { get; set; }
        public decimal nprcinctx { get; set; }
        public decimal nrstkpct { get; set; }
        public decimal nminrstk { get; set; }
        public decimal nmrsinctx { get; set; }
        public decimal nrepprice { get; set; }
        public decimal nrpprinctx { get; set; }
        public string xxx { get; set; }
    }
}
