//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class icvend
    {
        public string citemno { get; set; }
        public string cvendno { get; set; }
        public string cpartno { get; set; }
        public string cdescript { get; set; }
        public string cmeasure { get; set; }
        public Nullable<System.DateTime> dasof { get; set; }
        public short ldefault { get; set; }
        public int nvendltime { get; set; }
        public decimal ncost { get; set; }
        public decimal nlastcost { get; set; }
        public decimal nvndwarprd { get; set; }
        public Nullable<decimal> nNoItemOnPallet { get; set; }
        public string cWareHouse { get; set; }
        public string cOldUoM { get; set; }
        public Nullable<decimal> oldLast { get; set; }
        public Nullable<System.DateTime> dLastPo { get; set; }
        public Nullable<System.DateTime> dLastGR { get; set; }
    }
}
