//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class icwhse
    {
        public string cwarehouse { get; set; }
        public string cdescript { get; set; }
        public string caddr1 { get; set; }
        public string caddr2 { get; set; }
        public string ccity { get; set; }
        public string cstate { get; set; }
        public string czip { get; set; }
        public string ccountry { get; set; }
        public string cphone { get; set; }
        public string ccontact { get; set; }
        public string ctaxcode { get; set; }
        public string cinvtacc { get; set; }
        public string cintracc { get; set; }
        public string crevncode { get; set; }
    }
}
