//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasure
    {
        public int UnitOfMeasureId { get; set; }
        public string UnitOfMeasureDescription { get; set; }
        public string UnitOfMeasureCode { get; set; }
        public Nullable<bool> IsVoided { get; set; }
        public string Factor { get; set; }
        public string BaseCode { get; set; }
    }
}
