//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UOMBase
    {
        public int UOMBaseId { get; set; }
        public string UOMBase1 { get; set; }
        public string UOMBaseCode { get; set; }
    }
}
