//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassHierarchy
    {
        public long ClassHierarchyId { get; set; }
        public Nullable<int> ClassHierarchyRevNo { get; set; }
        public string Level1 { get; set; }
        public string Level2 { get; set; }
        public string Level3 { get; set; }
        public string Level4 { get; set; }
        public string Meta { get; set; }
        public string Path { get; set; }
        public Nullable<bool> IsVoided { get; set; }
    }
}
