//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class iciwh
    {
        public string cuid { get; set; }
        public string citemno { get; set; }
        public string cspeccode1 { get; set; }
        public string cspeccode2 { get; set; }
        public string cwarehouse { get; set; }
        public string csernum { get; set; }
        public string cinvtacc { get; set; }
        public string cintracc { get; set; }
        public string crevncode { get; set; }
        public Nullable<System.DateTime> dlastrecv { get; set; }
        public Nullable<System.DateTime> dlastrepd { get; set; }
        public int nmfgltime { get; set; }
        public decimal nsafestock { get; set; }
        public decimal nreordpt { get; set; }
        public decimal nreordqty { get; set; }
        public decimal nonhand { get; set; }
        public decimal nonorder { get; set; }
        public decimal ninprocess { get; set; }
        public decimal nallocate { get; set; }
        public decimal nbook { get; set; }
        public decimal nintransit { get; set; }
        public decimal ncost { get; set; }
        public decimal nlrecvcost { get; set; }
        public decimal ntotcost { get; set; }
        public decimal nlrepdcost { get; set; }
        public decimal nrmaonhand { get; set; }
        public decimal nrmacost { get; set; }
        public decimal nreprcost { get; set; }
        public string cbinlocation { get; set; }
        public string cdescript { get; set; }
        public Nullable<decimal> nQtyCommit { get; set; }
        public Nullable<decimal> nQtyBO { get; set; }
        public Nullable<decimal> lActive { get; set; }
        public Nullable<decimal> nMaxQty { get; set; }
        public Nullable<decimal> nBranchQty { get; set; }
        public Nullable<decimal> nInPick { get; set; }
        public Nullable<decimal> nCABook { get; set; }
    }
}
