//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class icunit
    {
        public string cmeasure { get; set; }
        public string cdescript { get; set; }
        public string csymbol { get; set; }
        public string cfsymbol { get; set; }
        public string cstatus { get; set; }
        public decimal ncnvqty { get; set; }
    }
}
