//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ProductId { get; set; }
        public string ProductSku { get; set; }
        public string ProductIdPrefix { get; set; }
        public string ProductBaseDescription { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string Brand { get; set; }
        public string TypeId { get; set; }
        public string UPC { get; set; }
        public string VendorId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> WeightUOMId { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<int> LengthUOMId { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<int> WidthUOMId { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<int> HeightUOMId { get; set; }
        public Nullable<int> UnitOfMeasureId { get; set; }
        public Nullable<bool> IsOneTimeProduct { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsVoided { get; set; }
        public Nullable<System.DateTime> DateTimeCreated { get; set; }
        public string CreatedBy { get; set; }
        public string ApprovedBy { get; set; }
        public string DisapprovalReason { get; set; }
        public Nullable<long> BrandId { get; set; }
        public Nullable<bool> NoUPCFound { get; set; }
        public Nullable<long> ClassId1 { get; set; }
        public Nullable<long> ClassId2 { get; set; }
        public Nullable<long> ClassId3 { get; set; }
        public Nullable<bool> IsSuitableChannels { get; set; }
        public Nullable<bool> IsSuitableWeb { get; set; }
        public Nullable<System.DateTime> DateTimeUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public string VendorPartNo { get; set; }
    
        public virtual UnitOfMeasureCategory UnitOfMeasureCategory { get; set; }
        public virtual UnitOfMeasureCategory UnitOfMeasureCategory1 { get; set; }
        public virtual UnitOfMeasureCategory UnitOfMeasureCategory2 { get; set; }
        public virtual UnitOfMeasureCategory UnitOfMeasureCategory3 { get; set; }
        public virtual Brand Brand1 { get; set; }
    }
}
