//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductManagementEntities : DbContext
    {
        public ProductManagementEntities()
            : base("name=ProductManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Flavor> Flavors { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Orientation> Orientations { get; set; }
        public virtual DbSet<Packaging> Packagings { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<SizeTitle> SizeTitles { get; set; }
        public virtual DbSet<Strength> Strengths { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }
        public virtual DbSet<UnitOfMeasureCategory> UnitOfMeasureCategories { get; set; }
        public virtual DbSet<UOMBase> UOMBases { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SystemErrorLog> SystemErrorLogs { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<ClassHierarchy> ClassHierarchies { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<ProductMapping> ProductMappings { get; set; }
        public virtual DbSet<Other> Other { get; set; }
    }
}
