//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public int SizeId { get; set; }
        public string SizeDescription { get; set; }
        public Nullable<int> SizeTitleId { get; set; }
        public string SizeCode { get; set; }
        public Nullable<bool> IsVoided { get; set; }
    
        public virtual SizeTitle SizeTitle { get; set; }
    }
}
