//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemErrorLog
    {
        public long SystemErrorLogId { get; set; }
        public string Module { get; set; }
        public string Method { get; set; }
        public string ErrorMessage { get; set; }
        public string SystemUser { get; set; }
        public Nullable<System.DateTime> LogDateTime { get; set; }
    }
}
